"""配置与多语言包。

- 语言即数据：新增语种/输出风格只需在 LANG_PACK 增加一项，不改逻辑代码。
- 配置文件跨平台定位（win/mac/linux），LLM 与默认选项可持久化，GUI 可读写。
"""
from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class LLMConfig:
    api_base: str
    api_key: str
    model: str


@dataclass
class LangPack:
    code: str
    pdf_subtitle: str        # PDF 页内字幕标签
    pdf_keyframe: str        # “关键帧”标签
    pdf_window: str          # “时间窗”标签
    pdf_footer: str
    prompt_language: str     # 给 LLM 的输出语言指令


LANG_PACK = {
    "zh": LangPack(
        code="zh",
        pdf_subtitle="字幕",
        pdf_keyframe="关键帧",
        pdf_window="时间窗",
        pdf_footer="由 Chalkpress 生成",
        prompt_language="全部用中文输出，专业术语首次出现时保留英文原文。",
    ),
    "zh-en": LangPack(
        code="zh-en",
        pdf_subtitle="字幕",
        pdf_keyframe="关键帧",
        pdf_window="时间窗",
        pdf_footer="由 Chalkpress 生成",
        prompt_language=(
            "用中文输出，每个关键术语后用括号附英文原文，"
            "例如：操作系统（Operating System）。"
        ),
    ),
    "en": LangPack(
        code="en",
        pdf_subtitle="Subtitles",
        pdf_keyframe="Keyframe",
        pdf_window="Time window",
        pdf_footer="Generated by Chalkpress",
        prompt_language="Respond entirely in English; keep proper nouns as-is.",
    ),
}


def lang_pack(code: str | None) -> LangPack:
    """未收录的语种回退中文；扩展语种在 LANG_PACK 里加条目即可。"""
    return LANG_PACK.get((code or "zh").lower()) or LANG_PACK["zh"]


def config_dir() -> Path:
    """跨平台用户数据目录（含 config.toml 与 logs/）。"""
    if sys.platform == "win32":
        base = Path(os.getenv("APPDATA", str(Path.home() / "AppData" / "Roaming")))
    elif sys.platform == "darwin":
        base = Path.home() / "Library" / "Application Support"
    else:
        base = Path(os.getenv("XDG_CONFIG_HOME", str(Path.home() / ".config")))
    return base / "chalkpress"


def config_path() -> Path:
    return config_dir() / "config.toml"


def logs_dir() -> Path:
    """运行日志目录（保留开关关闭时不会创建）。"""
    return config_dir() / "logs"


def _migrate_old_config() -> None:
    """v0.1 目录名 v2p2 → chalkpress 的一次性配置迁移。"""
    new = config_path()
    if new.is_file():
        return
    old = new.parent.parent / "v2p2" / "config.toml"
    if old.is_file():
        new.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(old, new)


def load_config_file() -> dict:
    _migrate_old_config()
    path = config_path()
    if not path.is_file():
        return {}
    try:
        import tomllib

        return tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def save_config_file(cfg: dict) -> Path:
    """极简 TOML 写入（支持 llm / options 两个 section，值为标量）。"""
    path = config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    for section, values in cfg.items():
        lines.append(f"[{section}]")
        for k, v in values.items():
            if v is None:
                continue
            if isinstance(v, bool):
                lines.append(f"{k} = {'true' if v else 'false'}")
            elif isinstance(v, (int, float)):
                lines.append(f"{k} = {v}")
            else:
                esc = str(v).replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'{k} = "{esc}"')
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def load_llm_config(api_base=None, api_key=None, model=None) -> LLMConfig | None:
    """优先级：CLI/GUI 参数 > 环境变量（CHALKPRESS_*，兼容旧 V2P2_*）> 配置文件 [llm]。

    三者齐备才启用 LLM 分析，否则返回 None（流水线降级为纯转写+PDF）。
    """
    file_cfg = load_config_file().get("llm", {})
    cfg = LLMConfig(
        api_base=(api_base or os.getenv("CHALKPRESS_API_BASE") or os.getenv("V2P2_API_BASE") or file_cfg.get("api_base") or "").strip().rstrip("/"),
        api_key=(api_key or os.getenv("CHALKPRESS_API_KEY") or os.getenv("V2P2_API_KEY") or file_cfg.get("api_key") or "").strip(),
        model=(model or os.getenv("CHALKPRESS_LLM_MODEL") or os.getenv("V2P2_LLM_MODEL") or file_cfg.get("model") or "").strip(),
    )
    return cfg if (cfg.api_base and cfg.api_key and cfg.model) else None


def normalize_settings(raw: dict) -> dict:
    """前端提交的散装配置 → 规范 config.toml 结构（原 GUI _save_settings 逻辑）。"""
    o = raw.get("options", {})
    app = raw.get("app", {})
    llm = raw.get("llm", {})
    options = {
        "summary_lang": o.get("summary_lang", "zh"),
        "zh_script": o.get("zh_script", "auto"),
        "auto_correct": bool(o.get("auto_correct", True)),
    }
    for k in ("asr_model", "scene_threshold", "min_gap"):
        if o.get(k) is not None:
            options[k] = o[k]
    cfg: dict = {"options": options,
                 "app": {"keep_log": bool(app.get("keep_log", True))}}
    base = (llm.get("api_base") or "").strip()
    key = (llm.get("api_key") or "").strip()
    model = (llm.get("model") or "").strip()
    if base and key and model:
        cfg["llm"] = {"api_base": base, "api_key": key, "model": model}
    return cfg
